version: '3'

services:
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: widgets
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password

    volumes:
      - ./db-data/mariadb:/var/lib/mysql