// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"myapp/adapter/controllers"
	"myapp/adapter/gateways"
	"myapp/usecases/interactors"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func NewTaskController() *controllers.TaskController {
	db := NewPostgresDatabaseHandler()
	taskRepositoryInterface := gateways.NewTaskRepository(db)
	taskUseCaseInterface := interactors.NewTaskUsecase(taskRepositoryInterface)
	taskController := controllers.NewTaskController(taskUseCaseInterface)
	return taskController
}

// wire.go:

func NewPostgresDatabaseHandler() *sql.DB {
	db, _ := sql.Open("postgres", "user=postgres password=password host=localhost port=5432 dbname=practice sslmode=disable")
	return db
}
